export const ProjectsInfo = [
  {
    heading: "Menu Card",
    problemStatement: "Design a visually engaging and user-friendly menu card for a coffee shop app that simplifies navigation and enhances customer interaction.",
    description: "The Menu Card project focuses on creating an intuitive interface where users can easily browse through coffee options, combos, and add-ons. Designed with Figma, this interactive layout balances modern design with usability, ensuring customers can quickly locate items and complete their orders. By focusing on clarity and simplicity, the design improves the digital dining experience for coffee lovers while maintaining brand aesthetics.",
    process: [
      "Conducted research on user behavior to identify how customers typically navigate digital menu cards within food and beverage apps.",
      "Outlined the key categories and product hierarchies to create a structured design flow for easy access and reduced cognitive load.",
      "Created wireframes to map out navigation patterns, ensuring all important sections like coffee categories, add-ons, and combos were well-placed.",
      "Developed high-fidelity mockups in Figma using consistent typography, color schemes, and spacing for a cohesive look.",
      "Tested the prototype with a small group of users to gather feedback on navigation speed and clarity of visual elements.",
      "Refined the design by addressing user pain points such as overly dense sections and unclear icons.",
      "Finalized the layout with an emphasis on readability, visual hierarchy, and delightful user experience.",
      "Delivered the interactive design ready for developer handoff with well-organized Figma components."
    ],
    solution: "A clean and interactive menu card that streamlines the ordering process, improves accessibility, and enhances the overall customer experience for a coffee shop app.",
    type: "design",
    featured: false,
    img: "/assets/projects/menuCard.png",
  },
  {
    heading: "Result Insight Hub",
    problemStatement: "Develop an interface that allows students and educators to clearly visualize and analyze performance data in an intuitive manner.",
    description: "The Result Insight Hub project is built around the idea of simplifying academic data presentation through clean and interactive design. Using Figma, the interface provides educators and students with a structured layout that highlights grades, trends, and performance insights. The design ensures easy interpretation of data while maintaining visual appeal, allowing users to track progress and make informed decisions efficiently.",
    process: [
      "Analyzed existing academic dashboards to understand the most effective ways of presenting student performance data.",
      "Identified the pain points in traditional systems, such as cluttered charts and confusing layouts.",
      "Mapped user journeys for both students and educators to understand their needs when reviewing results.",
      "Designed low-fidelity wireframes to organize insights into a clear, hierarchical layout for easy navigation.",
      "Developed polished Figma mockups that incorporated color-coded charts, performance indicators, and easy-to-read labels.",
      "Conducted usability testing to evaluate how well users could interpret the displayed data without external guidance.",
      "Iterated based on feedback to enhance clarity and reduce cognitive load for both primary and secondary data views.",
      "Finalized the design with accessible typography, strong contrasts, and modular components for scalability."
    ],
    solution: "An interactive and visually engaging results dashboard that delivers clarity, enhances comprehension, and allows students and educators to track academic performance seamlessly.",
    type: "design",
    featured: true,
    img: "/assets/projects/rih.png",
  },
  {
    heading: "Email Template",
    problemStatement: "Design a clean and visually appealing email template for a coffee shop app to improve customer engagement and brand communication.",
    description: "The Email Template project delivers a sleek and modern design tailored for digital communication in a coffee shop app. Built in Figma, the layout emphasizes readability, mobile responsiveness, and brand consistency. With a balanced structure of visuals and text, the design ensures effective communication of promotions, updates, and personalized offers, making it a powerful tool for customer retention and marketing.",
    process: [
      "Researched best practices for email marketing design to understand what increases open rates and customer engagement.",
      "Outlined the content structure focusing on headers, promotional banners, and call-to-action buttons.",
      "Created responsive wireframes to ensure the email layout works seamlessly across devices and screen sizes.",
      "Designed polished Figma templates with consistent branding, typography, and image placement.",
      "Ensured accessibility by selecting color contrasts and font sizes that work for all types of users.",
      "Tested the prototype across multiple email clients to confirm layout compatibility.",
      "Incorporated feedback from stakeholders to refine the balance between text and imagery.",
      "Delivered a final email template optimized for readability, usability, and brand appeal."
    ],
    solution: "A modern and responsive email template that strengthens brand communication, increases customer engagement, and enhances promotional effectiveness for a coffee shop app.",
    type: "design",
    featured: false,
    img: "/assets/projects/emailTemplate.svg",
  },
  {
    heading: "Libri Hub",
    problemStatement: "Design a simple, intuitive, and systematic interface for a library management platform to improve user accessibility and resource discovery.",
    description: "The Libri Hub project reimagines the digital library experience by creating a clean, structured, and user-friendly interface. Developed in Figma, the design emphasizes seamless navigation and resource categorization, allowing users to quickly browse, borrow, and manage digital content. By focusing on simplicity and functionality, the design enhances the overall user journey, making digital libraries more accessible and engaging.",
    process: [
      "Studied user expectations and challenges in navigating digital library platforms.",
      "Outlined the essential features required for quick search, borrowing, and content management.",
      "Sketched low-fidelity wireframes to plan the structure of key sections, including book categories and user dashboards.",
      "Created high-fidelity Figma designs that emphasized clean layouts, legible typography, and minimal clutter.",
      "Ensured intuitive navigation by organizing resources into well-defined categories.",
      "Conducted user feedback sessions to validate ease of navigation and identify areas for improvement.",
      "Refined the interface to address navigation gaps and enhance visual balance.",
      "Delivered the final structured design optimized for accessibility and scalability."
    ],
    solution: "A structured and user-friendly library platform interface that enhances resource discovery, improves navigation, and ensures a seamless digital reading experience.",
    type: "design",
    featured: true,
    img: "/assets/projects/libriHub.png",
  },
  {
    heading: "Coffee App Design",
    problemStatement: "Create an intuitive design for a coffee app’s login and signup screens to provide customers with a smooth onboarding experience.",
    description: "The Coffee App Design project is centered around enhancing customer onboarding through simple and engaging login and signup pages. Designed in Figma, the screens balance functionality with aesthetics, ensuring that users can quickly register, log in, and start ordering. The design uses familiar interaction patterns, clean layouts, and brand consistency to deliver a seamless experience that builds customer trust and loyalty.",
    process: [
      "Researched mobile app onboarding trends to identify features that maximize user retention.",
      "Outlined essential fields and simplified form structures for quicker registrations.",
      "Created wireframes to explore intuitive layout options for login and signup screens.",
      "Designed polished Figma mockups that prioritized usability and brand identity.",
      "Incorporated error states, hints, and validation feedback to guide users effectively.",
      "Tested the flow with sample users to evaluate ease of navigation and form completion rates.",
      "Refined spacing, typography, and visuals to create a welcoming and professional look.",
      "Prepared final designs ready for handoff with scalable components and design tokens."
    ],
    solution: "Clean and user-friendly login and signup screens that simplify customer onboarding, reduce friction, and create a seamless experience for a coffee app.",
    type: "design",
    featured: false,
    img: "/assets/projects/coffeeApp.png",
  },
  {
    heading: "Shopify",
    problemStatement: "Design an elegant and user-focused Shopify e-commerce website with visually appealing layouts and seamless product browsing.",
    description: "The Shopify project delivers a visually attractive and conversion-oriented e-commerce website design. Created in Figma, the layout emphasizes product presentation, intuitive navigation, and responsive design. High-quality imagery, clean typography, and strategically placed calls-to-action ensure an engaging user journey. The design enhances customer experience and empowers businesses to showcase products in a professional and compelling way.",
    process: [
      "Researched e-commerce design trends and customer behavior to understand what drives conversions.",
      "Outlined the essential shopping journey from homepage browsing to checkout completion.",
      "Designed wireframes focusing on ease of navigation and minimalistic layouts.",
      "Developed high-fidelity Figma mockups incorporating strong visuals and branding elements.",
      "Tested design prototypes to evaluate user interactions and ease of purchase flow.",
      "Refined layouts to reduce distractions and highlight primary call-to-action elements.",
      "Ensured responsiveness by testing across desktop, tablet, and mobile screen sizes.",
      "Finalized polished Shopify templates optimized for usability and visual appeal."
    ],
    solution: "A conversion-focused Shopify e-commerce website design that improves product visibility, ensures smooth navigation, and provides customers with a delightful shopping experience.",
    type: "design",
    featured: true,
    img: "/assets/projects/shopify.png",
  },
  {
    heading: "Friend's Portfolio Design",
    problemStatement: "Design a creative and interactive portfolio that showcases a professional’s projects with clarity and vibrant visuals.",
    description: "The Friend’s Portfolio Design project focuses on building a visually engaging platform to highlight creative work effectively. Crafted in Figma, the design emphasizes modern layouts, bold visuals, and clear navigation to help showcase projects in an attractive manner. By balancing aesthetics and usability, the portfolio offers a strong digital presence, enabling professionals to present their skills and achievements with confidence.",
    process: [
      "Researched modern portfolio design trends to identify features that stand out visually and functionally.",
      "Outlined content hierarchy to prioritize featured projects, skills, and contact information.",
      "Developed wireframes with a focus on storytelling through structured project sections.",
      "Designed high-fidelity mockups in Figma using vibrant visuals and interactive components.",
      "Conducted usability reviews to ensure that projects are easy to browse and navigate.",
      "Refined visuals, typography, and colors to align with a modern professional identity.",
      "Added interactive features like hover effects and transitions for enhanced engagement.",
      "Delivered the final design ensuring adaptability across devices and browsers."
    ],
    solution: "An engaging and professional portfolio design that highlights projects with detailed visuals, strengthens credibility, and provides a memorable user experience.",
    type: "design",
    featured: false,
    img: "/assets/projects/sumanthPortfolio.png",
  },
  {
    heading: "My Portfolio",
    problemStatement: "Design a personal portfolio to professionally showcase design expertise, creative projects, and user-centered solutions.",
    description: "The My Portfolio project is designed to serve as a comprehensive platform for presenting personal work and design journey. Built with Figma, the layout emphasizes clean structures, detailed project sections, and intuitive navigation. By combining storytelling with modern design elements, the portfolio enhances visibility, builds credibility, and provides an engaging experience for visitors exploring design capabilities.",
    process: [
      "Studied competitor portfolios to understand best practices and unique presentation styles.",
      "Outlined content flow to ensure seamless storytelling from introduction to detailed projects.",
      "Created wireframes to organize project showcases, testimonials, and contact sections.",
      "Designed polished Figma layouts emphasizing consistency, minimalism, and clarity.",
      "Integrated storytelling elements to provide context and insights for each project.",
      "Tested the design with peers to ensure readability and ease of navigation.",
      "Refined the portfolio to balance aesthetics and functionality for maximum engagement.",
      "Prepared final design with reusable components for future scalability and updates."
    ],
    solution: "A professional and user-friendly portfolio design that highlights creative expertise, showcases projects effectively, and creates a strong online presence.",
    type: "design",
    featured: false,
    img: "/assets/projects/portfolio.png",
  },
  {
    heading: "GenAITools",
    problemStatement: "Design a visually striking and modern interface for an AI tools platform to enhance usability and create a cohesive experience.",
    description: "The GenAITools project leverages color psychology, typography, and modern UI principles to deliver an innovative design. Created in Figma, the interface emphasizes functionality with a polished visual identity, ensuring that users can navigate features effortlessly. The design combines strong aesthetics with clarity, offering a seamless experience that reflects the sophistication of AI-powered platforms.",
    process: [
      "Researched AI platform interfaces to identify common usability challenges and opportunities.",
      "Outlined essential features to showcase tools and functionalities in an organized structure.",
      "Created low-fidelity wireframes to validate navigation and layout flows.",
      "Designed high-fidelity mockups in Figma with strong typography, balanced colors, and intuitive layouts.",
      "Conducted usability testing with potential users to refine navigation and hierarchy.",
      "Enhanced visual hierarchy with deliberate use of color contrast and spacing.",
      "Addressed accessibility considerations for inclusivity across a wide range of users.",
      "Finalized the design as a scalable and visually cohesive interface for AI-powered tools."
    ],
    solution: "A polished and intuitive AI tools platform design that combines usability with strong visual identity, ensuring a seamless and professional user experience.",
    type: "design",
    featured: true,
    img: "/assets/projects/genaitools.png",
  }
]
